# Setup
title:               yeungyung blog
tagline:             'Dreaming of ios developer'
description:         'Hello, I'm Ju yeungyung, born in 1999 and 23 years old this year. I transferred to Kookmin University in 2021 and am in the third grade of software convergence. My dream is to become an ios developer, and I am studying while listening to Swift lectures in the infron.'
url:                 https://yeungyung2019.github.io/
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              주연경
  url:               https://yeungyung2019.github.io/
  email:             rina0930@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
comment:
  provider:     "disqus"
  disqus:
    shortname:  "yeungyung"