# Setup
title:               yeungyung blog
tagline:             'Dreaming of ios developer'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://yeungyung2019.github.io/
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              주연경
  url:               https://yeungyung2019.github.io/
  email:             rina0930@kookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
comment:
  provider:     "disqus"
  disqus:
    shortname:  "yeungyung"